# This file was generated by nvfetcher, please do not modify it manually.
{ fetchgit, fetchurl, fetchFromGitHub, dockerTools }:
{
  gpu-screen-recorder-notification = {
    pname = "gpu-screen-recorder-notification";
    version = "4eaeba2a39874c76bfc71d69b97f7619f471747a";
    src = fetchgit {
      url = "https://repo.dec05eba.com/gpu-screen-recorder-notification";
      rev = "4eaeba2a39874c76bfc71d69b97f7619f471747a";
      fetchSubmodules = true;
      deepClone = false;
      leaveDotGit = false;
      sha256 = "sha256-i5rHyG66ZduibiL/zhriR/tS+yd5IVn2+heD3NiOluo=";
    };
    date = "2025-01-07";
  };
  gpu-screen-recorder-ui = {
    pname = "gpu-screen-recorder-ui";
    version = "92401d8bc8fa3cbc8017936eb1d18280199942e0";
    src = fetchgit {
      url = "https://repo.dec05eba.com/gpu-screen-recorder-ui";
      rev = "92401d8bc8fa3cbc8017936eb1d18280199942e0";
      fetchSubmodules = true;
      deepClone = false;
      leaveDotGit = false;
      sha256 = "sha256-dOsJvdW+cZ7U03XUEYgAA6GniQ85jl/HO9vRqzPLKEs=";
    };
    date = "2025-01-19";
  };
}
