[gpu-screen-recorder-notification]
src.git = "https://repo.dec05eba.com/gpu-screen-recorder-notification"
src.branch = "master"
fetch.git = "https://repo.dec05eba.com/gpu-screen-recorder-notification"
git.fetchSubmodules = true

[gpu-screen-recorder-ui]
src.git = "https://repo.dec05eba.com/gpu-screen-recorder-ui"
src.branch = "master"
fetch.git = "https://repo.dec05eba.com/gpu-screen-recorder-ui"
git.fetchSubmodules = true