# This file was generated by nvfetcher, please do not modify it manually.
{ fetchgit, fetchurl, fetchFromGitHub, dockerTools }:
{
  just-black = {
    pname = "just-black";
    version = "3.1.1";
    src = fetchurl {
      url = "https://Nur.gallery.vsassets.io/_apis/public/gallery/publisher/Nur/extension/just-black/3.1.1/assetbyname/Microsoft.VisualStudio.Services.VSIXPackage";
      name = "just-black-3.1.1.zip";
      sha256 = "sha256-fatJZquCDsLDFGVzBol2D6LIZUbZ6GzqcVEFAwLodW0=";
    };
  };
  local-lua-debugger-vscode = {
    pname = "local-lua-debugger-vscode";
    version = "0.3.3";
    src = fetchurl {
      url = "https://tomblind.gallery.vsassets.io/_apis/public/gallery/publisher/tomblind/extension/local-lua-debugger-vscode/0.3.3/assetbyname/Microsoft.VisualStudio.Services.VSIXPackage";
      name = "local-lua-debugger-vscode-0.3.3.zip";
      sha256 = "sha256-7uZHbhOa/GT9F7+xikaxuQXIGzre1q1uWTWaTJhi2UA=";
    };
  };
  lukin-vscode-theme = {
    pname = "lukin-vscode-theme";
    version = "0.1.5";
    src = fetchurl {
      url = "https://lukinco.gallery.vsassets.io/_apis/public/gallery/publisher/lukinco/extension/lukin-vscode-theme/0.1.5/assetbyname/Microsoft.VisualStudio.Services.VSIXPackage";
      name = "lukin-vscode-theme-0.1.5.zip";
      sha256 = "sha256-T6yCPCy2AprDqNTJk2ucN2EsCrODn4j/1oldSnQNigU=";
    };
  };
  nix-ide = {
    pname = "nix-ide";
    version = "0.4.2";
    src = fetchurl {
      url = "https://jnoortheen.gallery.vsassets.io/_apis/public/gallery/publisher/jnoortheen/extension/nix-ide/0.4.2/assetbyname/Microsoft.VisualStudio.Services.VSIXPackage";
      name = "nix-ide-0.4.2.zip";
      sha256 = "sha256-WOzHHQZlTdDoVB90GYhuEORNPLyv/lWZBNMrIzBTWW8=";
    };
  };
  sweet-dracula-monokai = {
    pname = "sweet-dracula-monokai";
    version = "1.1.14";
    src = fetchurl {
      url = "https://lefd.gallery.vsassets.io/_apis/public/gallery/publisher/lefd/extension/sweetdracula-monokai/1.1.14/assetbyname/Microsoft.VisualStudio.Services.VSIXPackage";
      name = "sweetdracula-monokai-1.1.14.zip";
      sha256 = "sha256-JUN2PQnkgqjNob//VFaGmZH5YmfM7ZXojvxkXR9MPh4=";
    };
  };
}
